### ISSUE TITLE
redrock access denied 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/our-chat#3]
You need to request access to each bedrock model or you get 

```
Traceback (most recent call last):
  File "/home/ochat/our-chat/tests/bedrock-test.py", line 77, in <module>
    response = bedrock.invoke_model(body=body, modelId=amodel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the InvokeModel operation: You don't have access to the model with the specified model ID.
```

**Comment by dirkpetersen** [comment]
fixed
